services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn squirrelco.wsgi:application -b 0.0.0.0:8000 --timeout 600
    ports:
      - "127.0.0.1:8002:8000"  # Only expose web service to localhost
    depends_on:
      - db
    networks:
      - squirrelnet

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - env.prod.db
    networks:
      - squirrelnet

volumes:
  postgres_data:

networks:
  squirrelnet:
    driver: bridge
    enable_ipv6: true
    ipam:
      config:
        - subnet: "2a01:4f8:1c1b:7011::1:0/112"
