services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn squirrelco.wsgi:application -b 0.0.0.0:8000 --timeout 600
    ports:
      - "127.0.0.1:8001:8000"
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - env.prod.db
volumes:
  postgres_data:

networks:
  mynetwork:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: "2a01:4f8:1c0c:826f::/64"